# PLD default plugin configuration for munin-node.
# Maintained in package because upstream no longer ships dists/tarball/plugins.conf.

[*]
env.logtail /usr/bin/logtail

env.logdir /var/log
env.logfile maillog

[netstat]
group proc

[amavis*]
user root
env.amavislog /var/log/maillog
env.logfile /var/log/maillog

[courier*]
user root
env.logfile /var/log/maillog

[mailman]
user mailman
group (mailman)

[bind9_rndc]
group (named)
env.querystats /var/lib/named/named.stats

[squid*]
group (squid)
#env.squidport 3128
#env.squiduser manager
#env.squidpasswd <SECRET>

[fw*]
group proc

[if*]
group proc

[dhcpd3]
user root
env.leasefile /var/lib/dhcpd/dhcpd.leases
env.configfile /etc/dhcpd.conf

[ip_*]
user root

[munin*]
user munin

[ping_*]
group adm

[port_*]
group proc

[processes]
group proc

[ps_*]
group proc

[psu_*]
group proc

[nfs*]
group proc

[entropy]
group proc

[open_*]
group proc

[nut*]
env.upsname SmartUPS
env.upshost 127.0.0.1

[df*]
#user root	# if you have mode 0000 /vservers dir
group proc

# Sane defaults for plugins from MuninExchange

[apache_smaps]
#user root	# if you have kernel with grsecurity
group proc
env.pname httpd.prefork
env.puser http

[dovecot]
user root
env.logfile /var/log/maillog

[php_eaccelerator]
env.user admin
env.password eAccelerator
env.url http://127.0.0.1/eaccelerator/control.php

[proftpd*]
user root
env.logfile /var/log/xferlog

[vsftpd*]
user root
env.logfile /var/log/vsftpd.log

[postgrey*]
user root
env.logfile /var/log/maillog

[nagiosstatus]
user root
env.statuslog /var/lib/nagios/status.dat

[freeradius]
user root
env.radius_log /var/log/freeradius/radius.log

[ipmitool_sensor*]
user root
timeout 20

[openvpn_clients]
user root
env.logfile /var/log/openvpn/status.log

[cupsys_pages]
user root
