# TODO
# - R: perl* should be autogenerated?
#
# Condtional build:
%bcond_with	sybase		# add Sybase support to munin-node
#
%include	/usr/lib/rpm/macros.perl
Summary:	Munin - the Linpro RRD data agent
Summary(pl):	Munin - agent danych RRD Linpro
Name:		munin
Version:	1.3.2
Release:	7
License:	GPL
Group:		Daemons
Source0:	http://dl.sourceforge.net/munin/%{name}_%{version}.tar.gz
# Source0-md5:	9eef4a53626cee0e088391c5deb8bd51
Source1:	%{name}-node.init
Source2:	%{name}.cron
Source3:	%{name}-apache.conf
Source4:	%{name}.logrotate
Patch0:		%{name}-Makefile.patch
Patch1:		%{name}-plugins.patch
Patch2:		%{name}-node-config.patch
Patch3:		%{name}-rrdtool12.patch
URL:		http://munin.sourceforge.net/
BuildRequires:	html2text
BuildRequires:	htmldoc
BuildRequires:	perl-devel
BuildRequires:	rpmbuild(macros) >= 1.268
Requires:	%{name}-common = %{version}-%{release}
Requires:	perl-Date-Manip
Requires:	perl-HTML-Template
Requires:	perl-Net-Server
Requires:	rrdtool >= 1.2.11
BuildArch:	noarch
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%define		_sysconfdir	/etc/%{name}
%define		htmldir		/home/services/httpd/html/%{name}

%description
Munin, formerly known as The Linpro RRD server, queries a number of
nodes, and processes the data using RRDtool and presents it on web
pages.

%description -l pl
Munin, znany poprzednio jako serwer RRD Linpro, odpytuje wiele wêz³ów
i przetwarza dane przy u¿yciu RRDtoola, a nastêpnie prezentuje je na
stronach WWW.

%package common
Summary:	Munin - the Linpro RRD data agent - common files
Summary(pl):	Munin - agent danych RRD Linpro - wspólne pliki
Group:		Daemons
Requires(postun):	/usr/sbin/groupdel
Requires(postun):	/usr/sbin/userdel
Requires(pre):	/bin/id
Requires(pre):	/usr/bin/getgid
Requires(pre):	/usr/sbin/groupadd
Requires(pre):	/usr/sbin/useradd

%description common
Munin, formerly known as The Linpro RRD server, queries a number of
nodes, and processes the data using RRDtool and presents it on web
pages.

%description common -l pl
Munin, znany poprzednio jako serwer RRD Linpro, odpytuje wiele wêz³ów
i przetwarza dane przy u¿yciu RRDtoola, a nastêpnie prezentuje je na
stronach WWW.

%package node
Summary:	Linpro RRD data agent
Summary(pl):	Agent danych RRD Linpro
Group:		Daemons
Requires(post,preun):	/sbin/chkconfig
Requires:	%{name}-common = %{version}-%{release}
Requires:	logtool
#Requires:	perl-Config-General
Requires:	perl-Net-Netmask
Requires:	perl-Net-SNMP
Requires:	perl-Net-Server
Requires:	perl-libwww
Requires:	procps >= 2.0.7
Requires:	rc-scripts >= 0.4.0.15
Requires:	sysstat

%description node
The Munin node package returns statistical data on the request of a
Munin server.

%description node -l pl
Pakiet Munin dla wêz³a zwraca dane statystyczne na ¿±danie serwera
Munin.

%prep
%setup -q
%patch0 -p1
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
%{__make} build

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT/etc/{rc.d/init.d,cron.d,logrotate.d}
install -d $RPM_BUILD_ROOT/var/log/archiv/munin

%{__make} install \
	DESTDIR=$RPM_BUILD_ROOT

install %{SOURCE1} $RPM_BUILD_ROOT/etc/rc.d/init.d/munin-node
install %{SOURCE2} $RPM_BUILD_ROOT/etc/cron.d/munin
install %{SOURCE4} $RPM_BUILD_ROOT/etc/logrotate.d/munin

install %{SOURCE3} $RPM_BUILD_ROOT%{_sysconfdir}/apache.conf

install node/node.d/README README.plugins

install dists/tarball/plugins.conf $RPM_BUILD_ROOT%{_sysconfdir}
ln -sf %{_sysconfdir}/plugins.conf $RPM_BUILD_ROOT%{_sysconfdir}/plugin-conf.d/munin-node

install server/munin-htaccess $RPM_BUILD_ROOT%{htmldir}/.htaccess
install server/style.css $RPM_BUILD_ROOT%{htmldir}/

%clean
rm -rf $RPM_BUILD_ROOT

%triggerin -- apache1 >= 1.3.33-2
%apache_config_install -v 1 -c %{_sysconfdir}/apache.conf

%triggerun -- apache1 >= 1.3.33-2
%apache_config_uninstall -v 1

%triggerin -- apache >= 2.0.0
%apache_config_install -v 2 -c %{_sysconfdir}/apache.conf

%triggerun -- apache >= 2.0.0
%apache_config_uninstall -v 2

%post node
if [ "$1" = "1" ] ; then
	/sbin/chkconfig --add munin-node
	%{_sbindir}/munin-node-configure --shell | sh
fi

%service munin-node restart "Munin Node agent"

%preun node
if [ "$1" = "0" ] ; then
	%service munin-node stop
	/sbin/chkconfig --del munin-node
fi

%pre common
%groupadd -g 158 munin
%useradd -o -u 158 -s /bin/false -g munin -c "Munin Node agent" -d /var/lib/munin munin

%postun common
if [ "$1" = "0" ]; then
	%userremove munin
	%groupremove munin
fi

%files
%defattr(644,root,root,755)
%attr(640,root,root) %config(noreplace) %verify(not md5 mtime size) /etc/cron.d/munin
%dir %{_sysconfdir}/templates
%{_sysconfdir}/templates/*
%config(noreplace) %verify(not md5 mtime size) %{_sysconfdir}/munin.conf
%attr(640,root,root) %config(noreplace) %verify(not md5 mtime size) %{_sysconfdir}/apache.conf
%attr(755,root,root) %{_sbindir}/munin-cron
%attr(755,root,root) %{_datadir}/munin/munin-graph
%attr(755,root,root) %{_datadir}/munin/munin-html
%attr(755,root,root) %{_datadir}/munin/munin-limits
%attr(755,root,root) %{_datadir}/munin/munin-update
%attr(755,munin,root) %dir %{htmldir}
%attr(644,munin,root) %{htmldir}/.htaccess
%attr(644,munin,root) %{htmldir}/style.css
%attr(755,munin,root) %dir %{_datadir}/munin/cgi
%attr(755,munin,root) %{_datadir}/munin/cgi/munin-cgi-graph
%{perl_vendorlib}/Munin.pm
%{_mandir}/man8/munin-graph*
%{_mandir}/man8/munin-update*
%{_mandir}/man8/munin-limits*
%{_mandir}/man8/munin-html*
%{_mandir}/man8/munin-cron*
%{_mandir}/man5/munin.conf*

%files common
%defattr(644,root,root,755)
%doc README.api README.plugins ChangeLog
# %{_docdir}/munin/README.config
%doc build/doc/*.{html,pdf}
%dir %{_sysconfdir}
%dir %{_datadir}/munin
%attr(750,munin,root) %dir /var/log/munin
%attr(750,munin,root) %dir /var/log/archiv/munin
%attr(770,munin,munin) %dir /var/lib/munin
%attr(640,root,root) %config(noreplace) %verify(not md5 mtime size) /etc/logrotate.d/munin

%files node
%defattr(644,root,root,755)
%dir %{_sysconfdir}/plugins
%config(noreplace) %verify(not md5 mtime size) %{_sysconfdir}/munin-node.conf
%attr(640,root,root) %config(noreplace) %verify(not md5 mtime size) %{_sysconfdir}/plugins.conf
%attr(640,root,root) %config(noreplace) %verify(not md5 mtime size) %{_sysconfdir}/plugin-conf.d/munin-node
%attr(754,root,root) /etc/rc.d/init.d/munin-node
%attr(755,root,root) %{_sbindir}/munin-run
%attr(755,root,root) %{_sbindir}/munin-node
%attr(755,root,root) %{_sbindir}/munin-node-configure
%attr(755,root,root) %{_sbindir}/munin-node-configure-snmp
%dir %{_datadir}/munin/plugins
%attr(755,root,root) %{_datadir}/munin/plugins/*
%if %{without sybase}
%exclude %{_datadir}/munin/plugins/sybase_space
%endif
%dir %attr(770,munin,munin) /var/lib/munin/plugin-state
%{_mandir}/man5/munin-node*
%{_mandir}/man8/munin-run*
%{_mandir}/man8/munin-node*
